spring:
  datasource:
    url: jdbc:mysql://localhost:3306/9room
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: update


kakao:
  client_id: 1b464b5659ec4c6f6247d997455fac1f
  redirect_uri: http://localhost:8080/callback

aws:
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: ${AWS_S3_BUCKET:9oorm-44-bucket}